### ISSUE TITLE
FR1. User Registration with External Oauth Providers

### ISSUE THREAD

**Issue by SukrutN** [WSU-4110/TrophyTracker#1]
|FR1. User Registration with External Oauth Providers|
|---|
|**Goal**: Enable users to register using external OAuth providers such as Google or Facebook, with the information stored in the database.
**Stakeholders:** Users, Database Administrators|
| **Description:** Users should have the option to register using their Google or Facebook accounts. The system will securely store the necessary user information in the database, ensuring compliance with privacy standards. The registration process will include steps for linking external accounts to the user profile.|
| **Origin:** Outlined in the initial project specification document, discussed and refined during team meetings.|
| **Version:** 1.0 |
|**Date:** 1/29/2024 |
| **Priority:** 1 |

**Comment by ThatZiv** [comment]
So far we just have GtiHub. We may expand to have other OAuth providers.
